version: '3.7'

services:
  database:
    image: postgres:11
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: wm_pass
      POSTGRES_USER: wm_user
      POSTGRES_DB: wm_local
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "6379:6379"

  migrations:
    build: .
    container_name: migrations
    restart: "no"
    depends_on:
      - cache
      - database
    environment:
      SECRET_KEY: secret
      SIMPLE_JWT_SIGNING_KEY: secret
      DB_HOST: database
      REDIS_HOST: cache
    command: ["migrations"]

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - migrations
    volumes:
      - "assets:/app/ass"
    environment:
      SECRET_KEY: secret
      SIMPLE_JWT_SIGNING_KEY: secret
      DB_HOST: database
      REDIS_HOST: cache

  web:
    image: "caddy:2.2.1-alpine"
    container_name: web
    depends_on:
      - app
      - migrations
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "assets:/assets"
      - "caddy_data:/data"
      - "caddy_config:/config"
    command: ["caddy", "file-server", "--root", "/assets"]

volumes:
  caddy_data:
  caddy_config:
  assets:
