[tool.black]
line-length = 100


[tool.isort]
line_length = 100
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
known_django = "django"
profile = "django"
src_paths = "app"


[tool.poetry]
name = "washmix_backend"
version = "0.1.0"
description = "Washmix"
authors = ["Evrone <api@evrone.com>"]


[tool.poetry.dependencies]
python = "~3.7"

# core + api
Django = "2.1.1"
djangorestframework = "3.9.0"
django-filter = "2.0.0"

# authentication
djoser = "^2.0.3"
djangorestframework-simplejwt = "^4.4.0"

# social authentication
social-auth-app-django = "^3.1.0"

# database
psycopg2-binary = "2.8.5"

# queue
django-dramatiq = "0.1.5"
dramatiq = {version = "1.4", extras = ["redis", "watch"]}

# money
stripe = "2.12.0"
twilio = "6.19.2"

# cache
django-cleanup = "2.1.0"
django-clear-cache = "0.3"

# static files
django-compressor = "2.2"
django-libsass = "0.7"
django-markdown-deux = "1.0.5"

# seo
django-robots = "3.1.0"
django-templated-mail = "1.1.1"

# other
requests = "2.20.1"
requests-oauthlib = "1.0.0"
arrow = "0.12.1"
drf-writable-nested = "0.5.4"
environs = "^8.0.0"
gunicorn = "^20.0.4"


[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^5.0.4"
Faker = "1.0.0"
django-debug-toolbar = "1.10.1"
fabric3 = "^1.14.post1"
pytest = "^5.4.3"


[build-system]
requires = ["poetry>=1.0.8"]
build-backend = "poetry.masonry.api"
