# Generated by Django 2.2.14 on 2020-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client", options={"verbose_name": "client", "verbose_name_plural": "clients"},
        ),
    ]
