# Generated by Django 2.2.17 on 2021-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="fix_tears",
            field=models.BooleanField(default=True, verbose_name="fix tears, rips"),
        ),
        migrations.AlterField(
            model_name="client",
            name="no_crease",
            field=models.CharField(
                blank=True,
                choices=[("all_pants", "All Pants"), ("jeans_only", "Jeans Only")],
                default="all_pants",
                max_length=20,
                verbose_name="no crease",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="starch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("heavy", "Heavy"),
                ],
                default="none",
                max_length=20,
                verbose_name="starch",
            ),
        ),
    ]
