# Generated by Django 2.2.15 on 2020-08-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="has_doormen",),
    ]
