# Generated by Django 2.2.16 on 2020-10-26 05:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_address",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="billing address"
            ),
        ),
    ]
