# Generated by Django 2.2.16 on 2020-11-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="subscription",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_client",
                to="subscriptions.Subscription",
                verbose_name="subscription of service",
            ),
        ),
    ]
