# Generated by Django 2.2.15 on 2020-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_auto_billing",
            field=models.BooleanField(default=True, verbose_name="automatically bill subscription"),
        ),
    ]
