# Generated by Django 2.2.16 on 2020-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="detergents",
            field=models.CharField(
                blank=True,
                choices=[("scented", "Scented"), ("hypo_allergenic", "Hypo-Allergenic")],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="fabric_softener",
            field=models.BooleanField(default=False, verbose_name="fabric softener"),
        ),
        migrations.AlterField(
            model_name="client",
            name="fix_tears",
            field=models.BooleanField(default=False, verbose_name="fix tears, rips"),
        ),
        migrations.AlterField(
            model_name="client",
            name="no_crease",
            field=models.CharField(
                blank=True,
                choices=[("all_pants", "All Pants"), ("jeans_only", "Jeans Only")],
                default="",
                max_length=20,
                verbose_name="no crease",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="starch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("heavy", "Heavy"),
                ],
                default="",
                max_length=20,
                verbose_name="starch",
            ),
            preserve_default=False,
        ),
    ]
