# Generated by Django 2.2.15 on 2020-08-07 08:14

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=20,
                null=True,
                unique=True,
                validators=[core.validators.validate_phone],
                verbose_name="phone",
            ),
        ),
    ]
