# Generated by Django 2.2.16 on 2020-10-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_billing_address_on_client"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="main_billing_address",),
    ]
