# Generated by Django 2.2.15 on 2020-09-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_is_auto_billing_on_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="subscription",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="billing.Subscription",
                verbose_name="subscription of service",
            ),
        ),
    ]
