# Generated by Django 2.2.16 on 2020-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_main_billing_address_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=250, verbose_name="address"),
        ),
    ]
