# Generated by Django 2.2.16 on 2020-10-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_set_foreign_keys"),
        ("users", "0003_change_subscription_relation_to_1_to_1_on_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="main_billing_address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.Address",
                verbose_name="main billing address",
            ),
        ),
    ]
