# Generated by Django 2.2.16 on 2020-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20201102_2215"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="kind",
            field=models.CharField(
                choices=[
                    ("interested", "Who interested in our services in future"),
                    (
                        "possible",
                        "Who uses only SMS orders and maybe will use web-application in future",
                    ),
                    ("storage", "Who interested in garment storage in our warehouse"),
                ],
                default="interested",
                max_length=20,
                verbose_name="kind",
            ),
        ),
    ]
