# Generated by Django 2.2.16 on 2020-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_change_subscription_relation_to_1_to_1_on_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="twilio_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Twilio ID"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="twilio_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Twilio ID"
            ),
        ),
    ]
