# Generated by Django 2.2.24 on 2022-05-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_logs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Logs",
            new_name="Log",
        ),
    ]
