# Generated by Django 2.2.28 on 2023-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20220524_0649"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="custom_delivery_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Private Note About Client"
            ),
        ),
    ]
