# Generated by Django 2.2.16 on 2020-11-26 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20201105_0039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birthday",
            field=models.DateField(
                default=django.utils.timezone.localdate, null=True, verbose_name="date of birthday"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="came_to_work",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                null=True,
                verbose_name="came out to work from",
            ),
        ),
    ]
