# Generated by Django 2.2.28 on 2023-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_client_custom_delivery_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="custom_delivery_note",
        ),
        migrations.AddField(
            model_name="client",
            name="private_note",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
