# Generated by Django 2.2.16 on 2020-11-26 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20201125_1927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="came_to_work",
            field=models.DateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="came out to work from"
            ),
        ),
    ]
