# Generated by Django 2.2.28 on 2023-10-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230407_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verified_email',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='verified email'),
        ),
    ]
