# Generated by Django 2.2.16 on 2020-11-27 03:12

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20201125_1927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="billing_address",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name="billing address"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="main_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.Address",
                verbose_name="main address",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="main_card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="billing.Card",
                verbose_name="main card",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="main_phone",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.Phone",
                verbose_name="main phone number",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_client",
                to="subscriptions.Subscription",
                verbose_name="subscription of service",
            ),
        ),
    ]
