# Generated by Django 2.2.28 on 2023-09-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230407_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='promo_sms_notification',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Promotional SMS Date'),
        ),
    ]
