# Generated by Django 2.2.28 on 2023-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_promo_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='scheduled_promo_sms',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Promotional SMS'),
        ),
    ]
