# Generated by Django 2.2.17 on 2020-12-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20201126_1912"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "Potential Customer",
                "verbose_name_plural": "Potential Customers",
            },
        ),
    ]
