# Generated by Django 2.2.28 on 2023-10-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_verified_email'),
        ('users', '0007_code'),
    ]

    operations = [
    ]
