# Generated by Django 2.2.28 on 2023-11-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
