# Generated by Django 2.2.28 on 2023-10-27 19:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20231025_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_phone], verbose_name='phone'),
        ),
    ]
