# Generated by Django 2.2.17 on 2020-12-11 06:57

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20201210_2157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[core.validators.validate_phone],
                verbose_name="phone",
            ),
        ),
    ]
