# Generated by Django 2.2.28 on 2023-11-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_promo_sms_notification'),
        ('users', '0009_employee_phone'),
    ]

    operations = [
    ]
