# Generated by Django 2.2.28 on 2023-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20231102_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verified_email_hash',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
