# Generated by Django 2.2.14 on 2020-07-29 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modules.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed date and time')),
                ('name', models.CharField(max_length=30, verbose_name='name of coupon')),
                ('amount_off', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='amount off')),
                ('percentage_off', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='percentage off')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='end date of coupon')),
                ('valid', models.BooleanField(default=True, verbose_name='is coupon valid for apply')),
                ('max_redemptions', models.IntegerField(default=1, verbose_name='maximum count of redemptions')),
                ('kind', models.CharField(choices=[(modules.enums.CouponType('FIRST'), 'FIRST'), (modules.enums.CouponType('PACKAGE'), 'PACKAGE')], default='FIRST', max_length=30, null=True, verbose_name='coupon type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed date and time')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='amount')),
                ('kind', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10, verbose_name='kind of transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_list', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed date and time')),
                ('stripe_card_id', models.TextField(verbose_name='Stripe card ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='card is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_list', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
