# Generated by Django 2.2.14 on 2020-07-31 11:10

import django.utils.timezone
from django.db import migrations, models

import modules.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("stripe_card_id", models.TextField(verbose_name="Stripe card ID")),
                ("is_active", models.BooleanField(default=False, verbose_name="card is active")),
            ],
            options={"verbose_name": "card", "verbose_name_plural": "cards",},
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name of coupon")),
                (
                    "amount_off",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=9, verbose_name="amount off"
                    ),
                ),
                (
                    "percentage_off",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=9, verbose_name="percentage off"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="end date of coupon"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="is coupon valid for apply"),
                ),
                (
                    "max_redemptions",
                    models.IntegerField(default=1, verbose_name="maximum count of redemptions"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (modules.enums.CouponType("FIRST"), "FIRST"),
                            (modules.enums.CouponType("PACKAGE"), "PACKAGE"),
                        ],
                        default="FIRST",
                        max_length=30,
                        null=True,
                        verbose_name="coupon type",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=9, verbose_name="amount"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                        verbose_name="kind of transaction",
                    ),
                ),
            ],
            options={"verbose_name": "transaction", "verbose_name_plural": "transactions",},
        ),
    ]
