# Generated by Django 2.2.15 on 2020-09-07 08:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="source of transaction (Stripe raw data)"
            ),
        ),
    ]
