# Generated by Django 2.2.16 on 2020-10-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription purchase"),
                    ("basket", "Order processing payment"),
                    ("delivery", "Payment for delivery"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="purpose of this invoice",
            ),
        ),
    ]
