# Generated by Django 2.2.17 on 2020-12-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_auto_20201210_2357"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="kind",
        ),
    ]
