# Generated by Django 2.2.15 on 2020-08-31 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="transaction",),
        migrations.AddField(
            model_name="transaction",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactiont",
                to="billing.Invoice",
                verbose_name="invoice",
            ),
        ),
    ]
