# Generated by Django 2.2.15 on 2020-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_auto_20200826_0705"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice", old_name="content_type", new_name="_content_type",
        ),
        migrations.RenameField(model_name="invoice", old_name="object_id", new_name="_object_id",),
        migrations.AlterField(
            model_name="coupon",
            name="value_off",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="for discount by percentage - it will be percentage in % of discount;for discount by amount - it will be amount in ¢ (cent) of discount",
                max_digits=9,
                verbose_name="value of discount",
            ),
        ),
    ]
