# Generated by Django 2.2.17 on 2021-01-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("billing", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("client", "stripe_id")},
        ),
    ]
