# Generated by Django 2.2.15 on 2020-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.BigIntegerField(default=0, verbose_name="discount in cents (¢)"),
            preserve_default=False,
        ),
    ]
