# Generated by Django 2.2.17 on 2021-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.BigIntegerField(default=0, verbose_name="amount, in cents (¢)"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.FloatField(default=0, verbose_name="discount, in cents (¢)"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("credit", "Credit by WashMix"),
                    ("subscription", "Subscription purchase"),
                    ("order", "POS order"),
                    ("one_time_payment", "One time payment"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="purpose of this invoice",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.BigIntegerField(default=0, verbose_name="amount, in cents (¢)"),
        ),
    ]
