# Generated by Django 2.2.19 on 2021-04-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_set_default_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("credit", "Credit by WashMix"),
                    ("subscription", "Subscription purchase"),
                    ("order", "POS order"),
                    ("one_time_payment", "One time payment"),
                    ("refund", "Refund"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="purpose of this invoice",
            ),
        ),
    ]
