# Generated by Django 2.2.15 on 2020-09-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_source_on_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_save_card",
            field=models.BooleanField(default=True, verbose_name="should we save the card"),
        ),
    ]
