# Generated by Django 2.2.17 on 2021-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_set_unique_together_on_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.FloatField(verbose_name="discount, in cents (¢)"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription purchase"),
                    ("basket", "Order processing payment"),
                    ("pickup", "Pickup delivery"),
                    ("dropoff", "Dropoff delivery"),
                    ("credit", "Credit"),
                    ("pos", "POS"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="purpose of this invoice",
            ),
        ),
    ]
