# Generated by Django 2.2.15 on 2020-08-31 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_invoice_on_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="billing.Invoice",
                verbose_name="invoice",
            ),
        ),
    ]
