# Generated by Django 2.2.16 on 2020-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_protect_on_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription purchase"),
                    ("order", "Order processing payment"),
                    ("delivery", "Payment for delivery"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="purpose of this invoice",
            ),
        ),
    ]
