# Generated by Django 2.2.17 on 2020-12-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_remove_coupon_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="max_redemptions",
        ),
    ]
