# Generated by Django 2.2.16 on 2020-10-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_change_purpose_on_invoice"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="coupon",),
    ]
