# Generated by Django 2.2.28 on 2023-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_refund_purpose_for_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purpose',
            field=models.CharField(choices=[('credit', 'Credit by WashMix'), ('subscription', 'Subscription purchase'), ('order', 'POS order'), ('one_time_payment', 'One time payment'), ('refund', 'Refund'), ('admin_charged_client', 'Admin charged the customer for remainder order')], default='subscription', max_length=20, verbose_name='purpose of this invoice'),
        ),
    ]
