# Generated by Django 2.2.17 on 2020-12-16 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_remove_coupon_max_redemptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_list",
                to="orders.Order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription purchase"),
                    ("basket", "Order processing payment"),
                    ("pickup", "Pickup delivery"),
                    ("dropoff", "Dropoff delivery"),
                    ("credit", "Credit"),
                ],
                default="subscription",
                max_length=20,
                verbose_name="purpose of this invoice",
            ),
        ),
    ]
