# Generated by Django 2.2.16 on 2020-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_invoice_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("coupon", "Coupon"),
                    ("credit_back", "Credit back"),
                    ("washmix", "WashMix"),
                ],
                max_length=10,
                verbose_name="provider of transaction",
            ),
        ),
    ]
