# Generated by Django 2.2.17 on 2020-12-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_auto_20201215_2005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_list",
                to="billing.Card",
                verbose_name="card",
            ),
        ),
    ]
