# Generated by Django 2.2.15 on 2020-08-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_change_fields_of_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="card is active"),
        ),
        migrations.AlterField(
            model_name="card",
            name="stripe_id",
            field=models.CharField(
                blank=True, max_length=100, unique=True, null=True, verbose_name="Stripe ID"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="stripe_id",
            field=models.CharField(
                blank=True, max_length=100, unique=True, null=True, verbose_name="Stripe ID"
            ),
        ),
    ]
