# Generated by Django 4.2.7 on 2023-11-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20231016_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purpose',
            field=models.CharField(choices=[('credit', 'Credit by WashMix'), ('subscription', 'Subscription purchase'), ('order', 'POS order'), ('one_time_payment', 'One time payment'), ('refund', 'Refund'), ('admin_charged_client', 'Admin charged client')], default='subscription', max_length=20, verbose_name='purpose of this invoice'),
        ),
    ]
