# Generated by Django 2.2.17 on 2020-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_auto_20201215_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.BigIntegerField(verbose_name="amount, in cents (¢)"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.BigIntegerField(verbose_name="discount, in cents (¢)"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.BigIntegerField(verbose_name="amount, in cents (¢)"),
        ),
    ]
