# Generated by Django 2.2.15 on 2020-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_set_unique_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="expiration_month",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="expiration month"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="expiration_year",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="expiration year"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="last",
            field=models.CharField(default="", max_length=4, verbose_name="last 4 digits"),
            preserve_default=False,
        ),
    ]
