# Generated by Django 2.2.15 on 2020-08-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_add_expiration_month_year_and_last_on_card"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon", options={"verbose_name": "coupon", "verbose_name_plural": "coupons"},
        ),
    ]
