# Generated by Django 2.2.17 on 2020-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_auto_20201215_2147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")],
                max_length=20,
                verbose_name="kind of transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("coupon", "Coupon"),
                    ("credit_back", "Credit back"),
                    ("washmix", "WashMix"),
                ],
                max_length=20,
                verbose_name="provider of transaction",
            ),
        ),
    ]
