# Generated by Django 2.2.17 on 2021-01-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_auto_20201223_2200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_list",
                to="orders.Order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_list",
                to="billing.Invoice",
                verbose_name="invoice",
            ),
        ),
    ]
