# Generated by Django 2.2.15 on 2020-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_add_meta_options_on_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="alterations",
            field=models.IntegerField(default=0, verbose_name="alterations discount"),
            preserve_default=False,
        ),
    ]
