# Generated by Django 2.2.15 on 2020-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_add_alterations_on_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("coupon", "Coupon"),
                    ("credit_back", "Credit back"),
                ],
                default="stripe",
                max_length=10,
                verbose_name="provider of transaction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.BigIntegerField(verbose_name="amount in cents"),
        ),
    ]
