version: 2.1

executors:
  build-executor:
    machine: true

aliases:
  - &build_environment
    executor: build-executor

  - &deploy_to_heroku
    - checkout
    - deploy_to_heroku

# Commands
commands:
  deploy_to_heroku:
    description: "Deploy applicaton to Heroku"
    steps:
      - run:
          command: |
            echo "Moved to Github Actions"
            # git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git ${CIRCLE_BRANCH}:master

jobs:
  "Deploy to Heroku":
    <<: *build_environment
    steps: *deploy_to_heroku

# // End of jobs

_release-filters: &release-filters
  branches:
    only:
      - heroku-test
      - master


workflows:
  deploy-to-heroku:
    jobs:
      - "Deploy to Heroku":
          filters:
            <<: *release-filters
