# Generated by Django 2.2.16 on 2020-10-15 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="alterations",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="alterations discount",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="dry_clean",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount on dry clean + press",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="laundry",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount on laundry + press",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="wash_fold",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount on wash & fold",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="alterations",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="alterations discount",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="dry_clean",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount on dry clean + press",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="laundry",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount on laundry + press",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="wash_fold",
            field=models.IntegerField(
                help_text="in percents",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount on wash & fold",
            ),
        ),
    ]
