# Generated by Django 2.2.16 on 2020-10-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription",
                to="billing.Invoice",
                verbose_name="invoice",
            ),
        ),
    ]
