# Generated by Django 2.2.17 on 2020-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20201210_2357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.BigIntegerField(verbose_name="price, in cents (¢)"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=models.BigIntegerField(verbose_name="price, in cents (¢)"),
        ),
    ]
