# Generated by Django 2.2.17 on 2021-01-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_auto_20201215_2147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="billing.Invoice",
                verbose_name="invoice",
            ),
        ),
    ]
