# Generated by Django 2.2.19 on 2021-03-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_remove_subscription_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                choices=[
                    ("payc", "Pay As You Clean"),
                    ("gold", "Gold Tier"),
                    ("platinum", "Platinum Tier"),
                ],
                max_length=20,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(
                choices=[
                    ("payc", "Pay As You Clean"),
                    ("gold", "Gold Tier"),
                    ("platinum", "Platinum Tier"),
                ],
                max_length=20,
                verbose_name="name",
            ),
        ),
    ]
