# Generated by Django 2.1.1 on 2019-04-05 13:08
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import modules.constant


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rest_framework_expiring_authtoken", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_long_lived", models.BooleanField(default=True)),
                (
                    "expiring_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_framework_expiring_authtoken.ExpiringToken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DropoffAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(default="")),
                ("state", models.CharField(default="", max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("zip_code", models.CharField(max_length=30)),
                ("title", models.CharField(default="", max_length=80)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoffaddress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("next_day_delivery", models.BooleanField(default=False)),
                ("same_day_delivery", models.BooleanField(default=False)),
                ("pick_up_from_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("pick_up_to_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("drop_off_from_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("drop_off_to_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("instructions", models.TextField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                ("total_cost", models.FloatField(default=0.0)),
                ("count", models.IntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                ("task_id_pickup", models.CharField(blank=True, editable=False, max_length=50)),
                ("task_id_dropoff", models.CharField(blank=True, editable=False, max_length=50)),
                (
                    "dropoff_address",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.DropoffAddress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item", models.TextField(default="")),
                ("cost", models.FloatField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="models.Order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("package_name", models.TextField(default="")),
                ("package_price", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PickupAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(default="")),
                ("state", models.CharField(default="", max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("zip_code", models.CharField(max_length=30)),
                ("title", models.CharField(default="", max_length=80)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickupaddress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(default="", max_length=15)),
                ("stripe_customer_id", models.TextField(null=True)),
                ("balance", models.FloatField(default=0)),
                (
                    "detergents",
                    models.CharField(
                        choices=[
                            (app.modules.constant.Detergents("Scented"), "Scented"),
                            (app.modules.constant.Detergents("Hypo-Allergenic"), "Hypo-Allergenic"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "starch",
                    models.CharField(
                        choices=[
                            (app.modules.constant.Starch("NONE"), "NONE"),
                            (app.modules.constant.Starch("LIGHT"), "LIGHT"),
                            (app.modules.constant.Starch("MEDIUM"), "MEDIUM"),
                            (app.modules.constant.Starch("HEAVY"), "HEAVY"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "no_crease",
                    models.CharField(
                        choices=[
                            (app.modules.constant.Crease("ALL_PANTS"), "ALL_PANTS"),
                            (app.modules.constant.Crease("JEANS_ONLY"), "JEANS_ONLY"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("fabric_softener", models.BooleanField(default=False)),
                ("fix_tears", models.BooleanField(default=False)),
                (
                    "package_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.PackageType",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stripe_card_id", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField(default="")),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_address",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="models.PickupAddress"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="addressorder",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.PickupAddress"
            ),
        ),
        migrations.AddField(
            model_name="addressorder",
            name="order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="models.Order"),
        ),
    ]
