# Generated by Django 2.2.19 on 2021-03-18 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
