# Generated by Django 2.2.24 on 2022-03-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.CharField(
                choices=[
                    ("new_order", "created new order"),
                    ("new_signup", "signed up"),
                    ("new_pickup_request", "created new pickup request"),
                    ("pickup_date_change", "changed the pickup date"),
                    ("pickup_request_canceled", "canceled the pickup request"),
                    ("dropoff_due_today", "drop-off is due today"),
                    ("potential_customer", "potential customer"),
                ],
                max_length=100,
                null=True,
                verbose_name="short description",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(
                choices=[
                    ("new_order", "created new order"),
                    ("new_signup", "signed up"),
                    ("new_pickup_request", "created new pickup request"),
                    ("pickup_date_change", "changed the pickup date"),
                    ("pickup_request_canceled", "canceled the pickup request"),
                    ("dropoff_due_today", "drop-off is due today"),
                    ("potential_customer", "potential customer"),
                ],
                max_length=80,
                verbose_name="notification type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user_triggered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Client",
                verbose_name="client",
            ),
        ),
    ]
