# Generated by Django 2.2.24 on 2022-05-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_auto_20220524_0645"),
        ("notifications", "0007_auto_20220527_1732"),
    ]

    operations = []
