# Generated by Django 2.2.28 on 2023-06-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.AlterModelOptions(
            name="smstemplate",
            options={"verbose_name": "SMS Template", "verbose_name_plural": "SMS Templates"},
        ),
        migrations.AddField(
            model_name="smstemplate",
            name="name",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
