# Generated by Django 2.2.28 on 2023-10-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230407_1432'),
        ('sms', '0002_auto_20230616_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Send SMS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.client',),
        ),
    ]
