# Generated by Django 2.2.14 on 2020-07-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("title", models.CharField(max_length=80, verbose_name="title of address")),
                ("address_line_1", models.TextField(verbose_name="address line 1")),
                ("address_line_2", models.TextField(verbose_name="address line 2")),
                ("state", models.CharField(max_length=30, verbose_name="state")),
            ],
            options={"verbose_name": "address", "verbose_name_plural": "addresses",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
            options={"verbose_name": "city", "verbose_name_plural": "cities",},
        ),
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("value", models.CharField(max_length=20, verbose_name="value")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zipcode_list",
                        to="locations.City",
                    ),
                ),
            ],
            options={"verbose_name": "zip code", "verbose_name_plural": "zip codes",},
        ),
    ]
