# Generated by Django 2.2.16 on 2020-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("title", models.CharField(max_length=80, verbose_name="title of address")),
                ("address_line_1", models.TextField(verbose_name="address line 1")),
                ("address_line_2", models.TextField(blank=True, verbose_name="address line 2")),
                (
                    "has_doormen",
                    models.BooleanField(default=False, verbose_name="is doorman at this address"),
                ),
            ],
            options={"verbose_name": "address", "verbose_name_plural": "addresses",},
        ),
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("value", models.CharField(max_length=20, unique=True, verbose_name="value")),
            ],
            options={"verbose_name": "zip code", "verbose_name_plural": "zip codes",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="name")),
                (
                    "zip_code_list",
                    models.ManyToManyField(related_name="city_list", to="locations.ZipCode"),
                ),
            ],
            options={"verbose_name": "city", "verbose_name_plural": "cities",},
        ),
    ]
