# Generated by Django 2.2.17 on 2021-01-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="delivery instructions"),
        ),
    ]
