# Generated by Django 2.2.15 on 2020-08-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_auto_20200826_0705"),
    ]

    operations = [
        migrations.RemoveField(model_name="address", name="state",),
    ]
