# Generated by Django 2.2.15 on 2020-08-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_add_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="has_doormen",
            field=models.BooleanField(default=False, verbose_name="is doorman at this address"),
        ),
    ]
