# Generated by Django 2.2.16 on 2020-10-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(max_length=250, verbose_name="address line 1"),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=250, verbose_name="address line 2"),
        ),
    ]
