# Generated by Django 2.2.14 on 2020-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_add_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="zipcode",
            name="value",
            field=models.CharField(max_length=20, unique=True, verbose_name="value"),
        ),
    ]
