# Generated by Django 2.2.14 on 2020-08-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_add_indexes"),
    ]

    operations = [
        migrations.RemoveField(model_name="zipcode", name="city",),
        migrations.AddField(
            model_name="city",
            name="zip_code_list",
            field=models.ManyToManyField(related_name="city_list", to="locations.ZipCode"),
        ),
    ]
