# Generated by Django 2.1.1 on 2020-07-09 08:39
import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc

import modules.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rest_framework_expiring_authtoken", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupons",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount_off", models.FloatField(default=0)),
                ("percentage_off", models.FloatField(default=0)),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.datetime(2020, 7, 9, 8, 39, 46, 959639, tzinfo=utc)
                    ),
                ),
                ("valid", models.BooleanField(default=True)),
                ("max_redemptions", models.IntegerField(default=1)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            (modules.enums.CouponType("FIRST"), "FIRST"),
                            (modules.enums.CouponType("PACKAGE"), "PACKAGE"),
                        ],
                        default="FIRST",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_long_lived", models.BooleanField(default=True)),
                (
                    "expiring_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_framework_expiring_authtoken.ExpiringToken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DropoffAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(default="")),
                ("state", models.CharField(default="", max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("zip_code", models.CharField(max_length=30)),
                ("title", models.CharField(default="", max_length=80)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoffaddress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("package_name", models.TextField(default="")),
                ("package_price", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PickupAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(default="")),
                ("state", models.CharField(default="", max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("zip_code", models.CharField(max_length=30)),
                ("title", models.CharField(default="", max_length=80)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickupaddress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.Product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(default="", max_length=15)),
                ("DOB", models.DateField(null=True)),
                ("joining_date", models.DateField(null=True)),
                ("SSN", models.CharField(max_length=15, null=True)),
                ("is_doormen", models.BooleanField(default=False)),
                ("stripe_customer_id", models.TextField(null=True)),
                ("balance", models.FloatField(default=0)),
                (
                    "detergents",
                    models.CharField(
                        choices=[
                            (modules.enums.Detergents("Scented"), "Scented"),
                            (modules.enums.Detergents("Hypo-Allergenic"), "Hypo-Allergenic"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "starch",
                    models.CharField(
                        choices=[
                            (modules.enums.Starch("NONE"), "NONE"),
                            (modules.enums.Starch("LIGHT"), "LIGHT"),
                            (modules.enums.Starch("MEDIUM"), "MEDIUM"),
                            (modules.enums.Starch("HEAVY"), "HEAVY"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "no_crease",
                    models.CharField(
                        choices=[
                            (modules.enums.Crease("ALL_PANTS"), "ALL_PANTS"),
                            (modules.enums.Crease("JEANS_ONLY"), "JEANS_ONLY"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "app_users",
                    models.CharField(
                        choices=[
                            (modules.enums.AppUsers("POTENTIAL_USERS"), "POTENTIAL_USERS"),
                            (modules.enums.AppUsers("REGULAR_USERS"), "REGULAR_USERS"),
                            (modules.enums.AppUsers("EMPLOYEE"), "EMPLOYEE"),
                        ],
                        default="REGULAR_USERS",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "authentication_provider",
                    models.CharField(
                        choices=[
                            (modules.enums.SignUp("facebook"), "facebook"),
                            (modules.enums.SignUp("google-oauth2"), "google-oauth2"),
                            (modules.enums.SignUp("washmix"), "washmix"),
                        ],
                        default="washmix",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("fabric_softener", models.BooleanField(default=False)),
                ("fix_tears", models.BooleanField(default=False)),
                ("is_coupon", models.BooleanField(default=False)),
                (
                    "package_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.PackageType",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stripe_card_id", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField(default="")),
                ("added_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
