# Generated by Django 2.2.16 on 2020-10-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_phone_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="title",
            field=models.CharField(max_length=80, verbose_name="title of phone"),
        ),
    ]
