# Generated by Django 2.2.14 on 2020-07-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200710_0225"),
    ]

    operations = [
        migrations.DeleteModel(name="Coupon",),
    ]
