# Generated by Django 2.2.15 on 2020-08-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_foreign_keys"),
    ]

    operations = [
        migrations.DeleteModel(name="Product",),
    ]
