# Generated by Django 2.2.16 on 2020-10-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="title",
            field=models.CharField(default="", max_length=80, verbose_name="title of address"),
            preserve_default=False,
        ),
    ]
