# Generated by Django 2.2.15 on 2020-08-07 08:14

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_unique_on_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[core.validators.validate_phone],
                verbose_name="number",
            ),
        ),
    ]
