# Generated by Django 2.2.14 on 2020-07-24 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed date and time')),
                ('item', models.TextField(default='')),
                ('cost', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed date and time')),
                ('next_day_delivery', models.BooleanField(default=False)),
                ('same_day_delivery', models.BooleanField(default=False)),
                ('pick_up_from_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pick_up_to_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('drop_off_from_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('drop_off_to_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructions', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('discount_description', models.TextField(blank=True)),
                ('discount_amount', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('dropoff_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_address_list', to='core.Address')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address_list', to='core.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
