# Generated by Django 2.2.17 on 2021-02-09 06:32

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("discount", models.FloatField(verbose_name="discount, in cents (¢)")),
                ("amount", models.BigIntegerField(verbose_name="amount, in cents (¢)")),
                (
                    "extra_items",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, verbose_name="extra items"
                    ),
                ),
            ],
            options={
                "verbose_name": "basket",
                "verbose_name_plural": "baskets",
                "ordering": ["-created"],
            },
            bases=(
                core.mixins.CalculatedAmountWithDiscountMixin,
                core.mixins.CalculatedDiscountMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="title of item"),
                ),
                ("image", models.ImageField(blank=True, upload_to="", verbose_name="image")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=False, verbose_name="is item visible on landing page"
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("amount", models.BigIntegerField(verbose_name="amount, in cents (¢)")),
                (
                    "count",
                    models.PositiveSmallIntegerField(default=1, verbose_name="count of items"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "pcs"),
                            ("set", "Set"),
                            ("lbs", "Pound"),
                            ("sq_ft", "Sqft"),
                            ("bag", "Bag"),
                            ("pleat", "Pleat"),
                        ],
                        default="pcs",
                        max_length=10,
                        verbose_name="unit of item",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list",
                        to="orders.Item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "price",
                "verbose_name_plural": "prices",
                "ordering": ["item__title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="title of service"),
                ),
                ("image", models.ImageField(blank=True, upload_to="", verbose_name="image")),
                (
                    "item_list",
                    models.ManyToManyField(
                        related_name="service_list",
                        through="orders.Price",
                        to="orders.Item",
                        verbose_name="items",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("count", models.PositiveSmallIntegerField(verbose_name="count of exact item")),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_list",
                        to="orders.Basket",
                        verbose_name="basket",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quantity_list",
                        to="orders.Price",
                        verbose_name="price",
                    ),
                ),
            ],
            options={
                "verbose_name": "quantity",
                "verbose_name_plural": "quantity",
            },
        ),
        migrations.AddField(
            model_name="price",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_list",
                to="orders.Service",
                verbose_name="service",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="accepted",
                        max_length=20,
                        verbose_name="status of order",
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("fail", "Fail")],
                        default="unpaid",
                        max_length=20,
                        verbose_name="payment info",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "is_save_card",
                    models.BooleanField(default=True, verbose_name="should we save the card"),
                ),
                (
                    "basket",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order",
                        to="orders.Basket",
                        verbose_name="basket",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created"],
            },
        ),
    ]
