# Generated by Django 2.2.14 on 2020-07-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="task_id_dropoff",),
        migrations.RemoveField(model_name="order", name="task_id_pickup",),
    ]
