# Generated by Django 2.2.16 on 2020-10-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("subscriptions", "0001_initial"),
        ("billing", "0002_auto_20201028_2238"),
        ("users", "0001_initial"),
        ("deliveries", "0003_auto_20201028_2238"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_list",
                to="users.Client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_list",
                to="billing.Coupon",
                verbose_name="coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_list",
                to="users.Employee",
                verbose_name="employee who handles this order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="request",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="deliveries.Request",
                verbose_name="request",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subscription",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="subscriptions.Subscription",
                verbose_name="subscription",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_list",
                to="users.Client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basket",
                to="billing.Invoice",
                verbose_name="invoice for basket",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="item_list",
            field=models.ManyToManyField(
                related_name="basket_list",
                through="orders.Quantity",
                to="orders.Price",
                verbose_name="items in basket",
            ),
        ),
        migrations.AlterUniqueTogether(name="price", unique_together={("service", "item")},),
        migrations.AlterUniqueTogether(name="order", unique_together={("basket", "request")},),
    ]
