# Generated by Django 2.2.16 on 2020-10-23 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_set_foreign_keys"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="invoice",),
        migrations.AddField(
            model_name="basket",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basket",
                to="billing.Invoice",
                verbose_name="invoice for basket",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_list",
            field=models.ManyToManyField(
                related_name="order_list", to="billing.Invoice", verbose_name="invoice list"
            ),
        ),
    ]
