# Generated by Django 2.2.15 on 2020-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="image"),
        ),
    ]
