# Generated by Django 2.2.16 on 2020-10-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="amount",),
    ]
