# Generated by Django 2.2.15 on 2020-09-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Request",),
    ]
