# Generated by Django 2.2.15 on 2020-08-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="value",
            field=models.BigIntegerField(verbose_name="value in cents (¢)"),
        ),
    ]
