# Generated by Django 2.2.16 on 2020-10-22 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("orders", "0001_initial"),
        ("deliveries", "0002_auto_20201021_2150"),
        ("billing", "0002_auto_20201021_2150"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_list",
                to="users.Client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.Delivery",
                verbose_name="delivery",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_list",
                to="users.Employee",
                verbose_name="employee that handles this order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="billing.Invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="request",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="deliveries.Request",
                verbose_name="request",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_list",
                to="users.Client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="item_list",
            field=models.ManyToManyField(
                related_name="basket_list",
                through="orders.Quantity",
                to="orders.Price",
                verbose_name="items in basket",
            ),
        ),
        migrations.AlterUniqueTogether(name="price", unique_together={("service", "item")},),
    ]
