# Generated by Django 2.2.15 on 2020-08-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=200, unique=True, verbose_name="title of item"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=200, unique=True, verbose_name="title of service"),
        ),
    ]
