# Generated by Django 2.2.16 on 2020-09-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantity_list",
                to="orders.Basket",
                verbose_name="basket",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quantity_list",
                to="orders.Price",
                verbose_name="price",
            ),
        ),
    ]
