# Generated by Django 2.2.16 on 2020-10-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
        ("orders", "0002_add_invoice_on_basket"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="order", unique_together={("basket", "request")},),
    ]
