# Generated by Django 2.2.15 on 2020-08-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_allow_blank_on_item"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="price", unique_together={("service", "item")},),
    ]
