# Generated by Django 2.2.17 on 2020-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20201210_2357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="amount",
            field=models.BigIntegerField(verbose_name="amount, in cents (¢)"),
        ),
    ]
