# Generated by Django 2.2.16 on 2020-10-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20201029_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
    ]
