# Generated by Django 2.2.15 on 2020-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_set_unique_together_on_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="quantity of items"),
        ),
    ]
