# Generated by Django 2.2.17 on 2020-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_auto_20201215_2147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={
                "ordering": ["-created"],
                "verbose_name": "basket",
                "verbose_name_plural": "baskets",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created"],
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="is_pdf_ready",
            field=models.BooleanField(default=False, verbose_name="PDF-report is ready"),
        ),
    ]
