# Generated by Django 2.2.17 on 2021-02-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_is_pdf_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_list",
                to="orders.Order",
                verbose_name="parent order",
            ),
        ),
    ]
