# Generated by Django 2.2.16 on 2020-11-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["title"], "verbose_name": "item", "verbose_name_plural": "items"},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={
                "ordering": ["service__title", "item__title"],
                "verbose_name": "price",
                "verbose_name_plural": "prices",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["title"],
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.AlterField(
            model_name="price",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "pcs"),
                    ("lbs", "Pound"),
                    ("sq_ft", "Square Foot"),
                    ("bag", "Bag"),
                    ("pleat", "Pleat"),
                ],
                default="pcs",
                max_length=10,
                verbose_name="unit of item",
            ),
        ),
    ]
