# Generated by Django 2.2.17 on 2021-03-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_remove_subscription_invoice"),
        ("orders", "0003_set_default_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_by_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="subscriptions.Subscription",
                verbose_name="subscription that used for discount by package",
            ),
        ),
    ]
