# Generated by Django 2.2.16 on 2020-10-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_subscription_and_coupon_on_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="status of order",
            ),
        ),
    ]
