# Generated by Django 2.2.15 on 2020-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_quantity_on_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="image"),
        ),
    ]
