# Generated by Django 2.2.19 on 2021-03-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_remove_subscription_invoice"),
        ("orders", "0004_add_discount_by_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="discount_by_subscription",
            new_name="bought_with_subscription",
        ),
    ]
