# Generated by Django 2.2.16 on 2020-11-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_auto_20201118_0116"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("fail", "Fail")],
                default="unpaid",
                max_length=20,
                verbose_name="payment info",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                default="accepted",
                max_length=20,
                verbose_name="status of order",
            ),
        ),
    ]
