# Generated by Django 2.2.17 on 2020-12-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_auto_20201215_2333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_pdf_ready",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="PDF-report is ready"
            ),
        ),
    ]
