# Generated by Django 2.2.16 on 2020-11-30 01:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_auto_20201119_2317"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="extra_items",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name="extra items"
            ),
        ),
    ]
