# Generated by Django 2.2.16 on 2020-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_change_status_on_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_save_card",
            field=models.BooleanField(default=True, verbose_name="should we save the card"),
        ),
    ]
