# Generated by Django 2.2.17 on 2021-01-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_auto_20201220_2215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket",
                to="billing.Invoice",
                verbose_name="invoice for basket",
            ),
        ),
    ]
