# Generated by Django 2.2.15 on 2020-08-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_image_on_service"),
    ]

    operations = [
        migrations.RenameField(model_name="price", old_name="price", new_name="value",),
        migrations.RemoveField(model_name="price", name="quantity",),
        migrations.AddField(
            model_name="price",
            name="count",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="count of items"),
        ),
        migrations.AddField(
            model_name="price",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Piece"),
                    ("lbs", "Pound"),
                    ("sq_ft", "Square Foot"),
                    ("bag", "Bag"),
                    ("pleat", "Pleat"),
                ],
                default="pcs",
                max_length=10,
                verbose_name="unit of item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=50, unique=True, verbose_name="title of item"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=50, unique=True, verbose_name="title of service"),
        ),
    ]
