# Generated by Django 2.2.19 on 2021-03-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_discount_by_subscription_on_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bought_with_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="subscriptions.Subscription",
                verbose_name="subscription that used for purchase this order",
            ),
        ),
    ]
