# Generated by Django 2.2.16 on 2020-11-30 06:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_extra_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="extra_items",
        ),
        migrations.AddField(
            model_name="basket",
            name="extra_items",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name="extra items"
            ),
        ),
    ]
