# Generated by Django 2.2.15 on 2020-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_add_fields_on_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_visible",
            field=models.BooleanField(
                default=False, verbose_name="is item visible on landing page"
            ),
        ),
    ]
