# Generated by Django 2.2.17 on 2021-01-12 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_auto_20210111_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="basket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="orders.Basket",
                verbose_name="basket",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="deliveries.Request",
                verbose_name="request",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="subscriptions.Subscription",
                verbose_name="subscription",
            ),
        ),
    ]
