# Generated by Django 2.2.24 on 2021-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_change_verbose_name_on_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="balance_after_purchase",
            field=models.BigIntegerField(
                default=0, verbose_name="customer balance after order, in cents (¢)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="balance_before_purchase",
            field=models.BigIntegerField(
                default=0, verbose_name="customer balance before order, in cents (¢)"
            ),
        ),
    ]
