# Generated by Django 2.2.16 on 2020-12-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_auto_20201129_2233"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={
                "ordering": ["item__title"],
                "verbose_name": "price",
                "verbose_name_plural": "prices",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "service", "verbose_name_plural": "services"},
        ),
    ]
