# Generated by Django 2.2.17 on 2020-12-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_auto_20201208_2132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "pcs"),
                    ("set", "Set"),
                    ("lbs", "Pound"),
                    ("sq_ft", "Sqft"),
                    ("bag", "Bag"),
                    ("pleat", "Pleat"),
                ],
                default="pcs",
                max_length=10,
                verbose_name="unit of item",
            ),
        ),
    ]
