# Custom Generated by Django 2.2.24 on 2023-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_auto_20211217_1930"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="unpaid_reminder_email_count",
        ),
        migrations.RemoveField(
            model_name="order",
            name="unpaid_reminder_email_time",
        ),
    ]
