# Generated by Django 2.2.24 on 2021-10-28 21:25

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("deliveries", "0008_change_ordering_on_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedDelivery",
            fields=[],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "ordering": ["-date", "sorting"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("deliveries.delivery",),
        ),
        migrations.CreateModel(
            name="ArchivedRequest",
            fields=[],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "ordering": ["-created"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("deliveries.request",),
        ),
    ]
