# Generated by Django 2.2.24 on 2021-11-08 17:29

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("archived", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedCustomer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[core.validators.validate_phone],
                        verbose_name="phone",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=100, verbose_name="full name"),
                ),
                ("zip_code", models.CharField(blank=True, max_length=20, verbose_name="zip code")),
                ("address", models.CharField(blank=True, max_length=250, verbose_name="address")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("interested", "Who interested in our services in future"),
                            (
                                "possible",
                                "Who uses only SMS orders and maybe will use web-application in future",
                            ),
                            ("storage", "Who interested in garment storage in our warehouse"),
                        ],
                        default="interested",
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Potential Customer",
                "verbose_name_plural": "Potential Customers",
            },
        ),
    ]
