# Generated by Django 2.2.24 on 2022-03-01 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archived", "0002_archivedcustomer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivedcustomer",
            options={
                "verbose_name": "Archived Customer",
                "verbose_name_plural": "Archived Customers",
            },
        ),
    ]
