# Generated by Django 2.2.28 on 2023-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archived", "0003_auto_20220301_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedcustomer",
            name="next_promo_email_schedule",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="next promo email schedule"
            ),
        ),
        migrations.AddField(
            model_name="archivedcustomer",
            name="promo_emails_sent_count",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, editable=False, verbose_name="promo emails sent count"
            ),
        ),
    ]
