# Generated by Django 2.2.28 on 2023-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived', '0003_auto_20220301_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedcustomer',
            name='promo_email_send_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Promotion Email Sending Time'),
        ),
        migrations.AddField(
            model_name='archivedcustomer',
            name='promo_email_sent_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Promotion Email Sent Count'),
        ),
    ]
