# Generated by Django 2.2.28 on 2023-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archived', '0004_auto_20230518_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedcustomer',
            name='promo_email_sent_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, verbose_name='promo email sent count'),
        ),
    ]
