# Generated by Django 2.2.28 on 2023-04-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archived', '0004_auto_20230420_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcustomer',
            name='promo_email_send_time',
        ),
        migrations.RemoveField(
            model_name='archivedcustomer',
            name='promo_email_sent_count',
        ),
    ]
