# Generated by Django 2.2.28 on 2023-09-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archived', '0004_auto_20230518_0658'),
        ('archived', '0006_auto_20230425_0400'),
    ]

    operations = [
    ]
