# Generated by Django 2.2.28 on 2023-11-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('branding', 'branding'), ('jet', 'jet'), ('branding.apps.BrandingConfig', 'branding.apps.BrandingConfig'), ('django.contrib.auth', 'django.contrib.auth'), ('django.contrib.contenttypes', 'django.contrib.contenttypes'), ('django.contrib.sessions', 'django.contrib.sessions'), ('django.contrib.messages', 'django.contrib.messages'), ('django.contrib.staticfiles', 'django.contrib.staticfiles'), ('debug_toolbar', 'debug_toolbar'), ('rest_framework', 'rest_framework'), ('djoser', 'djoser'), ('social_django', 'social_django'), ('swap_user', 'swap_user'), ('swap_user.to_named_email', 'swap_user.to_named_email'), ('drf_yasg', 'drf_yasg'), ('djangoql', 'djangoql'), ('django_filters', 'django_filters'), ('orders', 'orders'), ('users', 'users'), ('billing', 'billing'), ('locations', 'locations'), ('notifications', 'notifications'), ('deliveries', 'deliveries'), ('subscriptions', 'subscriptions'), ('archived', 'archived'), ('sms', 'sms'), ('permissions_manager', 'permissions_manager'), ('core', 'core')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions_manager.Application')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
    ]
