# Generated by Django 2.2.28 on 2023-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('permissions_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionassignment',
            name='permission',
        ),
        migrations.AddField(
            model_name='permissionassignment',
            name='permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
