# Generated by Django 2.2.28 on 2023-11-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions_manager', '0002_auto_20231101_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionassignment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='permissionassignment',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Permission'),
        ),
    ]
