# Generated by Django 2.2.16 on 2020-10-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="delivery", name="comment",),
        migrations.RemoveField(model_name="delivery", name="is_rush",),
        migrations.RemoveField(model_name="delivery", name="request",),
    ]
