# Generated by Django 2.2.16 on 2020-10-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("locations", "0001_initial"),
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_list",
                to="users.Client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_list",
                to="locations.Address",
                verbose_name="address to pickup and dropoff",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_list",
                to="users.Client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_list",
                to="users.Employee",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_list",
                to="deliveries.Schedule",
                verbose_name="recurring schedule of delivery",
            ),
        ),
    ]
