# Generated by Django 2.2.16 on 2020-10-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_set_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="amount",
            field=models.BigIntegerField(default=0, verbose_name="amount in cents (¢)"),
            preserve_default=False,
        ),
    ]
