# Generated by Django 2.2.16 on 2020-10-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_add_amount_on_delivery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-pickup_date"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
    ]
