# Generated by Django 2.2.17 on 2021-01-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_set_foreign_keys"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={
                "ordering": ["-created"],
                "verbose_name": "request",
                "verbose_name_plural": "requests",
            },
        ),
    ]
