# Generated by Django 2.2.16 on 2020-11-27 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_auto_20201029_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_list",
                to="deliveries.Schedule",
                verbose_name="recurring schedule for request",
            ),
        ),
    ]
