# Generated by Django 2.2.17 on 2021-02-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_set_default_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="custom_amount",
            field=models.BigIntegerField(
                default=0, verbose_name="custom delivery price, in cents (¢)"
            ),
        ),
    ]
