# Generated by Django 2.2.17 on 2021-02-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_change_request_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="rush_amount",
            field=models.BigIntegerField(
                default=0, verbose_name="rush delivery price, in cents (¢)"
            ),
            preserve_default=False,
        ),
    ]
