# Generated by Django 2.2.17 on 2020-12-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_auto_20201126_1912"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-sorting"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="sorting",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="sorting order"
            ),
        ),
    ]
