# Generated by Django 2.2.17 on 2020-12-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_auto_20201217_0035"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-date", "sorting", "employee"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
    ]
