# Generated by Django 2.2.16 on 2020-10-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_add_ordering_for_delivery"),
    ]

    operations = [
        migrations.RemoveField(model_name="delivery", name="amount",),
    ]
