# Generated by Django 2.2.17 on 2020-12-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_auto_20201208_2132"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["date", "-sorting"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
    ]
