# Generated by Django 2.2.17 on 2021-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_add_custom_amount_on_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="is_custom",
            field=models.BooleanField(default=False, verbose_name="is a custom delivery price"),
        ),
    ]
