# Generated by Django 2.2.17 on 2020-12-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0007_auto_20201208_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery",
                to="billing.Invoice",
                verbose_name="invoice for delivery",
            ),
        ),
    ]
