# Generated by Django 2.2.17 on 2021-01-12 03:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0007_auto_20201220_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="billing.Invoice",
                verbose_name="invoice for delivery",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (1, "Monday"),
                        (2, "Tuesday"),
                        (3, "Wednesday"),
                        (4, "Thursday"),
                        (5, "Friday"),
                    ],
                    verbose_name="day of week",
                ),
                max_length=5,
                size=None,
                verbose_name="recurring pickup days",
            ),
        ),
    ]
