# Generated by Django 2.2.19 on 2021-03-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0007_change_working_days"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-date", "sorting"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
    ]
