# Generated by Django 2.2.17 on 2020-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0008_auto_20201208_2138"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-date", "-priority"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="sorting",
        ),
        migrations.AddField(
            model_name="delivery",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="priority"),
        ),
    ]
