# Generated by Django 2.2.24 on 2022-03-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0008_change_ordering_on_delivery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["date", "-kind", "-request__is_rush"],
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
            },
        ),
    ]
