# Generated by Django 2.2.17 on 2020-12-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0009_auto_20201208_2139"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="note",
            field=models.TextField(blank=True, verbose_name="note on delivery"),
        ),
    ]
