# Generated by Django 2.2.17 on 2020-12-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0010_delivery_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancelled", "Cancelled"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                default="accepted",
                max_length=20,
                verbose_name="current status",
            ),
        ),
    ]
