# Generated by Django 2.2.24 on 2022-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0011_auto_20220617_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="nonworkingday",
            name="day",
            field=models.CharField(
                choices=[
                    ("1", "Monday"),
                    ("2", "Tuesday"),
                    ("3", "Wednesday"),
                    ("4", "Thursday"),
                    ("5", "Friday"),
                    ("6", "Saturday"),
                    ("7", "Sunday"),
                ],
                max_length=20,
                verbose_name="day",
            ),
        ),
    ]
