# Generated by Django 2.2.28 on 2023-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_auto_20220623_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_show', 'No Show')], default='accepted', max_length=20, verbose_name='current status'),
        ),
    ]
