# Generated by Django 2.2.28 on 2023-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0013_auto_20230407_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="unpaid_reminder_email_count",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, editable=False, verbose_name="Unpaid Order Reminder Email"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="unpaid_reminder_email_time",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Reminder Email Time"
            ),
        ),
    ]
