# Generated by Django 2.2.28 on 2023-07-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_auto_20230523_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='route_end',
            field=models.DateTimeField(null=True, verbose_name='delivery ended at'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route_start',
            field=models.DateTimeField(null=True, verbose_name='delivery started at'),
        ),
    ]
