# Generated by Django 2.2.28 on 2023-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_auto_20230523_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='generated_by_admin',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Generated by admin'),
        ),
    ]
