# Generated by Django 2.2.28 on 2023-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_request_generated_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_show', 'No Show'), ('in_store_accepted', 'In store accepted'), ('in_store_completed', 'In store completed')], default='accepted', max_length=20, verbose_name='current status'),
        ),
    ]
