# Generated by Django 2.2.28 on 2023-10-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_categorizeroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorizeroute',
            options={'verbose_name_plural': 'Categorized Routes'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='in_store',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Instore delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_show', 'No Show'), ('in_store_dropoff', 'In Store: dropoff'), ('in_store_pickup', 'In Store: pickup')], default='accepted', max_length=20, verbose_name='current status'),
        ),
    ]
