# Generated by Django 2.2.28 on 2023-10-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_auto_20231013_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='in_store',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Instore delivery'),
        ),
    ]
