# Generated by Django 2.2.28 on 2023-10-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0017_delivery_in_store'),
        ('deliveries', '0016_categorizeroute'),
    ]

    operations = [
    ]
