name: test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: foobar
      SIMPLE_JWT_SIGNING_KEY: spam
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.poetry/bin:$PATH"
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Check Poetry version
        run: |
          poetry --version
      - name: Run tests
        run: |
          poetry install
          poetry run pytest app/
