# Generated by Django 2.2.15 on 2020-09-07 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_set_foreign_keys"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="date for delivery")),
                ("start", models.TimeField(verbose_name="start of delivery interval")),
                ("end", models.TimeField(verbose_name="end of delivery interval")),
            ],
            options={
                "verbose_name": "delivery interval",
                "verbose_name_plural": "delivery intervals",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_list",
                        to="locations.Address",
                        verbose_name="address to pickup and dropoff",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_list",
                        to="users.Client",
                        verbose_name="client",
                    ),
                ),
                (
                    "dropoff_interval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET,
                        related_name="+",
                        to="pickups.Interval",
                        verbose_name="drop",
                    ),
                ),
                (
                    "pickup_interval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pickups.Interval",
                        verbose_name="pickup interval",
                    ),
                ),
            ],
            options={"verbose_name": "request pickup", "verbose_name_plural": "request pickups",},
        ),
    ]
