# Generated by Django 2.2.16 on 2020-10-05 03:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_auto_20201001_2044"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "is_rush",
                    models.BooleanField(default=False, verbose_name="is a rush / urgent delivery"),
                ),
                (
                    "days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("mon", "Monday"),
                                ("tue", "Tuesday"),
                                ("wed", "Wednesday"),
                                ("thu", "Thursday"),
                                ("fri", "Friday"),
                                ("sat", "Saturday"),
                                ("sun", "Sunday"),
                            ],
                            max_length=10,
                            verbose_name="day of week",
                        ),
                        max_length=7,
                        size=None,
                        verbose_name="recurring pickup days",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active recurring delivery"),
                            ("paused", "Paused recurring delivery"),
                        ],
                        max_length=20,
                        verbose_name="status of recurring delivery",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_list",
                        to="users.Client",
                        verbose_name="client",
                    ),
                ),
            ],
            options={"verbose_name": "schedule", "verbose_name_plural": "schedules",},
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="creation date and time"),
                ),
                (
                    "changed",
                    models.DateTimeField(auto_now=True, verbose_name="last changed date and time"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "is_rush",
                    models.BooleanField(default=False, verbose_name="is a rush / urgent delivery"),
                ),
                ("pickup_date", models.DateField(verbose_name="date for pickup")),
                ("pickup_start", models.TimeField(verbose_name="start of pickup interval")),
                ("pickup_end", models.TimeField(verbose_name="end of pickup interval")),
                ("dropoff_date", models.DateField(verbose_name="date for dropoff")),
                ("dropoff_start", models.TimeField(verbose_name="start of dropoff interval")),
                ("dropoff_end", models.TimeField(verbose_name="end of dropoff interval")),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_list",
                        to="locations.Address",
                        verbose_name="address to pickup and dropoff",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_list",
                        to="users.Client",
                        verbose_name="client",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_list",
                        to="users.Employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_list",
                        to="pickups.Schedule",
                        verbose_name="schedule of delivery",
                    ),
                ),
            ],
            options={"verbose_name": "delivery", "verbose_name_plural": "deliveries",},
        ),
    ]
