# Generated by Django 2.2.16 on 2020-10-02 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="kind",
            field=models.CharField(
                choices=[
                    ("one_time", "Usual (one time) delivery"),
                    ("recurring", "Recurring (periodic) delivery"),
                ],
                default="one_time",
                max_length=20,
                verbose_name="kind of delivery",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("mon", "Monday"),
                        ("tue", "Tuesday"),
                        ("wed", "Wednesday"),
                        ("thu", "Thursday"),
                        ("fri", "Friday"),
                        ("sat", "Saturday"),
                        ("sun", "Sunday"),
                    ],
                    max_length=10,
                    verbose_name="day of week",
                ),
                default=list,
                max_length=7,
                size=None,
                verbose_name="recurring pickup days",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active recurring delivery"),
                    ("paused", "Paused recurring delivery"),
                ],
                max_length=20,
                null=True,
                verbose_name="status of recurring delivery",
            ),
        ),
    ]
