# Generated by Django 2.2.15 on 2020-09-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Interval",),
    ]
