# Generated by Django 2.2.16 on 2020-10-05 04:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_list",
                to="pickups.Schedule",
                verbose_name="recurring schedule of delivery",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (1, "Monday"),
                        (2, "Tuesday"),
                        (3, "Wednesday"),
                        (4, "Thursday"),
                        (5, "Friday"),
                        (6, "Saturday"),
                        (7, "Sunday"),
                    ],
                    verbose_name="day of week",
                ),
                max_length=7,
                size=None,
                verbose_name="recurring pickup days",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active recurring delivery"),
                    ("paused", "Paused recurring delivery"),
                ],
                max_length=20,
                verbose_name="status of schedule",
            ),
        ),
    ]
