# Generated by Django 2.2.15 on 2020-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0002_delete_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="comment",
            field=models.TextField(blank=True, verbose_name="comment"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_rush",
            field=models.BooleanField(default=False, verbose_name="is a rush / urgent delivery"),
        ),
    ]
