# Generated by Django 2.2.16 on 2020-10-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0002_add_kind_on_delivery"),
    ]

    operations = [
        migrations.RemoveField(model_name="delivery", name="kind",),
    ]
