# Generated by Django 2.2.15 on 2020-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0003_add_comment_and_is_rush_on_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="dropoff_date",
            field=models.DateField(verbose_name="date for dropoff"),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="pickup_date",
            field=models.DateField(verbose_name="date for pickup"),
        ),
    ]
