# Generated by Django 2.2.16 on 2020-09-11 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_change_subscription_relation_to_1_to_1_on_client"),
        ("pickups", "0004_remove_auto_now_add_from_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_list",
                to="users.Employee",
            ),
        ),
    ]
